---
openapi: 3.0.3
info:
  title: JPA Sample Application
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Local server
paths:
  /v1/manager:
    get:
      tags:
      - Manager Resource
      parameters:
      - name: include_deleted
        in: query
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Manager"
  /v1/manager/{id}:
    get:
      tags:
      - Manager Resource
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManageResponse"
components:
  schemas:
    LocalDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50
    ManageResponse:
      type: object
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
        team_id:
          format: int32
          type: integer
        team_name:
          type: string
    Manager:
      type: object
      properties:
        id:
          format: int32
          type: integer
        team:
          $ref: "#/components/schemas/Team"
        name:
          type: string
        createdAt:
          $ref: "#/components/schemas/LocalDateTime"
        updatedAt:
          $ref: "#/components/schemas/LocalDateTime"
    Team:
      type: object
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
        createdAt:
          $ref: "#/components/schemas/LocalDateTime"
        updatedAt:
          $ref: "#/components/schemas/LocalDateTime"
