---
openapi: 3.1.0
info:
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: JPA Sample Application
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Local server
components:
  schemas:
    ErrorMessage:
      type: object
      properties:
        message:
          type: string
        detailMessage:
          type: string
    LocalDateTime:
      type: string
      format: date-time
      examples:
      - 2022-03-10T12:15:50
    Manager:
      type: object
      properties:
        id:
          type: integer
          format: int32
        team:
          $ref: "#/components/schemas/Team"
        name:
          type: string
        createdAt:
          $ref: "#/components/schemas/LocalDateTime"
        updatedAt:
          $ref: "#/components/schemas/LocalDateTime"
    Team:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        createdAt:
          $ref: "#/components/schemas/LocalDateTime"
        updatedAt:
          $ref: "#/components/schemas/LocalDateTime"
    TeamCreateRequest:
      type: object
      properties:
        name:
          type: string
paths:
  /v1/manager:
    get:
      parameters:
      - name: include_deleted
        in: query
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Manager"
      summary: List
      tags:
      - Manager Resource
  /v1/manager/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Manager"
      summary: Get By Id Cross
      tags:
      - Manager Resource
  /v1/team:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TeamCreateRequest"
        required: true
      responses:
        "201": {}
        "409":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "500": {}
        "400":
          description: Bad Request
      summary: Post V 2
      tags:
      - Team Resource
    get:
      parameters:
      - name: include_deleted
        in: query
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Team"
      summary: List
      tags:
      - Team Resource
  /v1/team/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Team"
      summary: Get By Id Cross
      tags:
      - Team Resource
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
      summary: Delete
      tags:
      - Team Resource
