
    create sequence team_seq start with 1 increment by 1;

    create table manager (
        id integer generated by default as identity,
        is_active boolean default true,
        team_id integer unique,
        created_at timestamp DEFAULT CURRENT_TIMESTAMP not null,
        updated_at timestamp DEFAULT CURRENT_TIMESTAMP not null,
        name varchar(255) not null,
        primary key (id)
    );

    comment on column manager.name is
        '監督名';

    create table player (
        id integer generated by default as identity,
        is_active boolean default true not null,
        team_id integer not null,
        uniform_number integer not null,
        created_at timestamp DEFAULT CURRENT_TIMESTAMP not null,
        updated_at timestamp DEFAULT CURRENT_TIMESTAMP not null,
        position varchar(16) not null,
        name varchar(64) not null,
        primary key (id),
        unique (team_id, uniform_number)
    );

    comment on column player.uniform_number is
        '背番号';

    comment on column player.position is
        'ポジション';

    comment on column player.name is
        '選手名';

    create table player_transfer_history (
        id integer generated by default as identity,
        player_id integer not null,
        from_team_id integer,
        to_team_id integer not null,
        transferred_at timestamp DEFAULT CURRENT_TIMESTAMP not null,
        created_at timestamp DEFAULT CURRENT_TIMESTAMP not null,
        primary key (id),
        check (from_team_id is null or from_team_id <> to_team_id)
    );

    comment on column player_transfer_history.transferred_at is
        '移籍日時';

    create index idx_player_transfer_history_player_transferred_at
        on player_transfer_history (player_id, transferred_at);

    create table team (
        id integer not null,
        is_active boolean default true not null,
        created_at timestamp DEFAULT CURRENT_TIMESTAMP not null,
        updated_at timestamp DEFAULT CURRENT_TIMESTAMP not null,
        name varchar(64) not null unique,
        primary key (id)
    );

    alter table if exists manager
       add constraint FKdil9hd6t80irdaebtwvj49hy2
       foreign key (team_id)
       references team;

    alter table if exists player
       add constraint FKdvd6ljes11r44igawmpm1mc5s
       foreign key (team_id)
       references team;

    alter table if exists player_transfer_history
       add constraint FK_player_transfer_history_player
       foreign key (player_id)
       references player;

    alter table if exists player_transfer_history
       add constraint FK_player_transfer_history_from_team
       foreign key (from_team_id)
       references team;

    alter table if exists player_transfer_history
       add constraint FK_player_transfer_history_to_team
       foreign key (to_team_id)
       references team;

insert into public.team (id, is_active, created_at, updated_at, name) values  (1, true, '2023-09-03 23:26:34', '2023-09-03 23:26:41', '阪神タイガース'),         (2, true, '2023-09-03 14:28:12', '2023-09-03 14:28:12', '広島カープ'),         (3, true, '2023-09-03 14:28:12', '2023-09-03 14:28:12', '横浜DeNAベイスターズ'),         (4, true, '2023-09-03 14:28:12', '2023-09-03 14:28:12', '読売ジャイアンツ'),         (5, true, '2023-09-03 14:28:12', '2023-09-03 14:28:12', '東京ヤクルトスワローズ'),         (6, true, '2023-09-03 14:28:12', '2023-09-03 14:28:12', '中日ドラゴンズ'),         (7, true, '2023-09-03 14:32:51', '2023-09-03 14:32:51', 'オリックス・バファローズ'),         (8, true, '2023-09-03 14:32:51', '2023-09-03 14:32:51', '千葉ロッテマリーンズ'),         (9, true, '2023-09-03 14:32:51', '2023-09-03 14:32:51', '福岡ソフトバンクホークス'),         (10, true, '2023-09-03 14:32:51', '2023-09-03 14:32:51', '楽天イーグルス'),         (11, true, '2023-09-03 14:32:51', '2023-09-03 14:32:51', '北海道日本ハムファイターズ'),         (12, true, '2023-09-03 14:32:51', '2023-09-03 14:32:51', '埼玉西武ライオンズ');
insert into public.manager (id, is_active, team_id, created_at, updated_at, name) values  (1, true, 1, '2023-09-03 15:42:02', '2023-09-03 15:42:02', '岡田彰布'),         (2, true, 2, '2023-09-03 15:43:42', '2023-09-03 15:43:42', '新井貴浩'),         (3, true, 3, '2023-09-03 15:43:42', '2023-09-03 15:43:42', '三浦大輔'),         (4, true, 4, '2023-09-03 15:43:42', '2023-09-03 15:43:42', '原辰徳'),         (5, true, 5, '2023-09-03 15:43:42', '2023-09-03 15:43:42', '高津臣吾'),         (6, true, 6, '2023-09-03 15:43:42', '2023-09-03 15:43:42', '立浪和義'),         (7, true, 7, '2023-09-03 15:47:25', '2023-09-03 15:47:25', '中嶋聡'),         (8, true, 8, '2023-09-03 15:47:25', '2023-09-03 15:47:25', '吉井理人'),         (9, true, 9, '2023-09-03 15:47:25', '2023-09-03 15:47:25', '藤本博史'),         (10, true, 10, '2023-09-03 15:47:25', '2023-09-03 15:47:25', '石井一久'),         (11, true, 11, '2023-09-03 15:47:25', '2023-09-03 15:47:25', '松井稼頭央'),         (12, true, 12, '2023-09-03 15:47:25', '2023-09-03 15:47:25', '新庄剛志');
insert into public.player (id, is_active, team_id, created_at, updated_at, name, uniform_number, position) select     i,     true,     ((i - 1) % 12) + 1,     '2024-01-01 00:00:00',     '2024-01-01 00:00:00',     'ダミー選手' || lpad(i::text, 3, '0'),     ((i - 1) / 12) + 1,     case ((i - 1) % 6)         when 0 then 'P'         when 1 then 'C'         when 2 then 'IF'         when 3 then 'OF'         when 4 then 'IF'         else 'OF'     end from generate_series(1, 120) as s(i);
insert into public.player_transfer_history (player_id, from_team_id, to_team_id, transferred_at, created_at) select p.id, null, p.team_id, p.created_at, p.created_at from public.player p;
ALTER SEQUENCE team_seq RESTART WITH 13;
ALTER SEQUENCE manager_id_seq RESTART WITH 13;
ALTER SEQUENCE player_id_seq RESTART WITH 121;
ALTER SEQUENCE player_transfer_history_id_seq RESTART WITH 121;
